commands:
  Passwords:
    - title: "Password 12-char simple"
      cmd: "pwgen -1 12"
    - title: "Password 16-char secure"
      cmd: "pwgen -1 -s 16"
    - title: "Password 20-char secure (no ambiguous)"
      cmd: "pwgen -1 -svB 20"
    - title: "Password 24-char symbols"
      cmd: "pwgen -1 -sy 24"
    - title: "Password 32-char secure"
      cmd: "pwgen -1 -s 32"
    - title: "Password 32-char secure (no ambiguous)"
      cmd: "pwgen -1 -svB 32"
    - title: "5 secure 16-char passwords"
      cmd: "pwgen -s 16 5"
    - title: "Pronounceable 12-char"
      cmd: "pwgen -1 12"
    - title: "Random 32 bytes (hex)"
      cmd: "openssl rand -hex 32"
    - title: "Random UUID"
      cmd: "cat /proc/sys/kernel/random/uuid"
  Hashing:
    - title: "SHA256 /etc/passwd"
      cmd: "sha256sum /etc/passwd"
    - title: "SHA512 /etc/passwd"
      cmd: "sha512sum /etc/passwd"
    - title: "MD5 'example'"
      cmd: "echo -n example | md5sum"
    - title: "SHA256 'secret'"
      cmd: "echo -n secret | sha256sum"
    - title: "SHA1 /etc/hosts"
      cmd: "sha1sum /etc/hosts"
    - title: "SHA1 current dir files"
      cmd: "find . -maxdepth 1 -type f -exec sha1sum {} + | sort"
    - title: "SHA256 of /etc/passwd"
      cmd: "sha256sum /etc/passwd"
    - title: "SHA512 of /etc/passwd"
      cmd: "sha512sum /etc/passwd"
    - title: "MD5 of 'example'"
      cmd: "echo -n 'example' | md5sum"
    - title: "Random 24 bytes (base64)"
      cmd: "openssl rand -base64 24"
  Crypto:
    - title: "Random 128-bit (hex)"
      cmd: "openssl rand -hex 16"
    - title: "Random 256-bit (base64)"
      cmd: "openssl rand -base64 32"
    - title: "Random password /dev/urandom"
      cmd: "tr -dc 'A-Za-z0-9!@#$%_' < /dev/urandom | head -c 20"
    - title: "Entropy available"
      cmd: "cat /proc/sys/kernel/random/entropy_avail"
    - title: "Random 32 bytes SHA256"
      cmd: "head -c 32 /dev/urandom | sha256sum"
    - title: "Random 32-bit number"
      cmd: "od -An -N4 -tu4 < /dev/urandom"
  Processes:
    - title: "Top memory processes"
      cmd: "ps aux --sort=-%mem | head -n 10"
    - title: "Top CPU processes"
      cmd: "ps aux --sort=-%cpu | head -n 10"
    - title: "Process tree (first 30)"
      cmd: "ps -axo pid,ppid,cmd --forest | head -n 30"
    - title: "Process count"
      cmd: "ps -e | wc -l"
    - title: "Threads in current shell"
      cmd: "ps -o nlwp $$"
  System:
    - title: "Pretty uptime"
      cmd: "uptime -p"
    - title: "Uptime & load"
      cmd: "uptime"
    - title: "Memory usage"
      cmd: "free -h"
    - title: "Disk usage /"
      cmd: "df -h /"
    - title: "Kernel version"
      cmd: "uname -r"
    - title: "OS release"
      cmd: "grep PRETTY_NAME /etc/os-release"
    - title: "UTC time"
      cmd: "date -u"
  Network:
    - title: "IP addresses brief"
      cmd: "ip -brief addr"
    - title: "Listening ports"
      cmd: "ss -tuln"
    - title: "DNS resolve example.com"
      cmd: "getent hosts example.com"
    - title: "Ping 1.1.1.1 (3x)"
      cmd: "ping -c 3 1.1.1.1"
    - title: "HTTP headers example.com"
      cmd: "curl -I https://example.com"
    - title: "Default route"
      cmd: "ip route | head -n 1"
  Files:
    - title: "Largest 10 items ."
      cmd: "du -ah . | sort -hr | head -n 10"
    - title: "Recent 10 files"
      cmd: "ls -lt | head -n 10"
    - title: "Disk usage top dirs"
      cmd: "du -h --max-depth=1 | sort -h"
    - title: "File count recursive"
      cmd: "find . -type f | wc -l"
    - title: "First PATH dir entries"
      cmd: "ls -1 $(echo $PATH | cut -d: -f1) | head -n 20"
  Encoding:
    - title: "Base64 encode 'example'"
      cmd: "echo -n example | base64"
    - title: "Base64 decode 'ZXhhbXBsZQ=='"
      cmd: "echo ZXhhbXBsZQ== | base64 -d"
    - title: "Hex dump /etc/hosts (32B)"
      cmd: "head -c 32 /etc/hosts | hexdump -C"
    - title: "String to hex 'secret'"
      cmd: "echo -n secret | xxd -p"
    - title: "Hex to string 68656c6c6f"
      cmd: "echo 68656c6c6f | xxd -r -p"
  Basic:
    - title: "12-char password"
      cmd: "pwgen -1 12"
    - title: "16-char password"
      cmd: "pwgen -1 16"
    - title: "20-char secure"
      cmd: "pwgen -1 -s 20"
    - title: "20-char secure (no ambiguous)"
      cmd: "pwgen -1 -svB 20"
    - title: "24-char mixed password"
      cmd: "pwgen -1 24"
  Advanced:
    - title: "20-char secure (no vowels, no ambiguous)"
      cmd: "pwgen -1 -svBv 20"
    - title: "Five secure 16-char passwords"
      cmd: "pwgen -s 16 5"
    - title: "Ten secure 12-char (no ambiguous)"
      cmd: "pwgen -svB 12 10"
    - title: "64-char /dev/urandom set"
      cmd: "tr -dc 'A-Za-z0-9!@#$%^&*()_+' < /dev/urandom | head -c 64"
    - title: "Pronounceable secure 12-char"
      cmd: "pwgen -1 -sv 12"
  Utilities:
    - title: "List listening ports"
      cmd: "ss -tuln"
    - title: "Top 10 memory processes"
      cmd: "ps aux --sort=-%mem | head -n 10"
    - title: "System uptime"
      cmd: "uptime -p"
    - title: "IP addresses (brief)"
      cmd: "ip -brief addr"
    - title: "Open file limit"
      cmd: "ulimit -n"
