---
version: '3'

tasks:
    util-hello:
        desc: Test task that prints a message
        cmds:
            - echo "✓ Task execution successful!"
            - echo "This task was selected in the TUI and executed automatically"

    util-echo:
        desc: Another simple test
        cmds:
            - echo "Test command executed from TUI"
            - date

    util-list-files:
        desc: List files in current directory
        cmds:
            - ls -l

    util-disk-usage:
        desc: Show disk usage
        cmds:
            - df -h

    sys-memory:
        desc: Show memory usage
        cmds:
            - free -h

    sys-uptime:
        desc: Show system uptime
        cmds:
            - uptime

    net-ip:
        desc: Show IP address
        cmds:
            - ip addr show

    net-connections:
        desc: Show network connections
        cmds:
            - netstat -tulnp || ss -tulnp

    sys-users:
        desc: Show logged in users
        cmds:
            - who

    util-date:
        desc: Show current date and time
        cmds:
            - date

    util-calendar:
        desc: Show current month calendar
        cmds:
            - cal

    util-pwd:
        desc: Print current directory
        cmds:
            - pwd

    dir-make:
        desc: 'Create a directory. Usage: task dir-make -- DIR="test-dir"'
        cmds:
            - mkdir -p '{{.DIR | default "test-dir"}}'

    dir-remove:
        desc: 'Remove a directory. Usage: task dir-remove -- DIR="test-dir"'
        cmds:
            - rmdir '{{.DIR | default "test-dir"}}' || true

    file-copy:
        desc: 'Copy a file. Usage: task file-copy -- SRC="/etc/hosts" DEST="hosts.copy"'
        cmds:
            - cp '{{.SRC | default "/etc/hosts"}}' '{{.DEST | default "hosts.copy"}}'

    file-move:
        desc: 'Move/rename a file. Usage: task file-move -- SRC="hosts.copy" DEST="hosts.backup"'
        cmds:
            - mv '{{.SRC | default "hosts.copy"}}' '{{.DEST | default "hosts.backup"}}' || true

    file-remove:
        desc: 'Remove a file. Usage: task file-remove -- FILE="hosts.backup"'
        cmds:
            - rm -f '{{.FILE | default "hosts.backup"}}'

    file-cat:
        desc: 'Display contents of a file. Usage: task file-cat -- FILE="/etc/hostname"'
        cmds:
            - cat '{{.FILE | default "/etc/hostname"}}'

    file-head:
        desc: 'Display first N lines of a file. Usage: task file-head -- FILE="/etc/passwd" LINES=5'
        cmds:
            - head -n '{{.LINES | default 5}}' '{{.FILE | default "/etc/passwd"}}'

    file-tail:
        desc: 'Display last N lines of a file. Usage: task file-tail -- FILE="/etc/passwd" LINES=5'
        cmds:
            - tail -n '{{.LINES | default 5}}' '{{.FILE | default "/etc/passwd"}}'

    file-search:
        desc: 'Search for a term in a file. Usage: task file-search -- TERM="root" FILE="/etc/passwd"'
        cmds:
            - grep '{{.TERM | default "root"}}' '{{.FILE | default "/etc/passwd"}}'

    file-count-lines:
        desc: 'Count lines in a file. Usage: task file-count-lines -- FILE="/etc/passwd"'
        cmds:
            - wc -l '{{.FILE | default "/etc/passwd"}}'

    sys-processes:
        desc: List running processes
        cmds:
            - ps aux

    sys-kernel:
        desc: Show kernel version
        cmds:
            - uname -r

    sys-info:
        desc: Show system information
        cmds:
            - uname -a

    sys-block-devices:
        desc: List block devices
        cmds:
            - lsblk

    sys-usb:
        desc: List USB devices
        cmds:
            - lsusb || true

    sys-pci:
        desc: List PCI devices
        cmds:
            - lspci || true

    net-dns:
        desc: 'Resolve a hostname. Usage: task net-dns -- HOST="google.com"'
        cmds:
            - dig '{{.HOST | default "google.com"}}' || nslookup '{{.HOST | default "google.com"}}'

    net-ping:
        desc: 'Ping a host. Usage: task net-ping -- HOST="google.com"'
        cmds:
            - ping -c 4 '{{.HOST | default "google.com"}}'

    apt-update:
        desc: Update package lists (Debian/Ubuntu)
        cmds:
            - sudo apt update

    apt-upgrade:
        desc: Upgrade installed packages (Debian/Ubuntu)
        cmds:
            - sudo apt upgrade -y

    ask:
        desc: 'Asks for variables and prints them. Usage: task ask -- NAME="John" LASTNAME="Doe"'
        cmds:
            - echo 'Hello, {{.NAME}} {{.LASTNAME}}!'

    art:
        desc: Print some ASCII art
        silent: true
        cmds:
            - |
                echo "   _____         _      "
                echo "  |_   _|__  ___| |__   "
                echo "    | |/ _ \\/ __| '_ \\  "
                echo "    | |  __/\\__ \\ | | | "
                echo "    |_|\\___||___/_| |_| "
                echo ""
                echo "ASCII ART DEMO!"

    about:
        desc: Info about Task TUI
        silent: true
        cmds:
            - |
                echo "Task TUI - A simple frontend for Taskfile.dev"
                echo "Repository: https://github.com/Mgldvd/task-gui"
                echo "Version: Experimental"
