---
version: '3'

tasks:
    util-hello:
        desc: Test task that prints a message
        cmds:
            - echo "✓ Task execution successful!"
            - echo "This task was selected in the GUI and executed automatically"

    util-echo:
        desc: Another simple test
        cmds:
            - echo "Test command executed from GUI"
            - date

    util-list-files:
        desc: List files in current directory
        cmds:
            - ls -l

    util-disk-usage:
        desc: Show disk usage
        cmds:
            - df -h

    sys-memory:
        desc: Show memory usage
        cmds:
            - free -h

    sys-uptime:
        desc: Show system uptime
        cmds:
            - uptime

    net-ip:
        desc: Show IP address
        cmds:
            - ip addr show

    net-connections:
        desc: Show network connections
        cmds:
            - netstat -tulnp || ss -tulnp

    sys-users:
        desc: Show logged in users
        cmds:
            - who

    util-date:
        desc: Show current date and time
        cmds:
            - date

    util-calendar:
        desc: Show current month calendar
        cmds:
            - cal

    util-pwd:
        desc: Print current directory
        cmds:
            - pwd

    dir-make:
        desc: Create a directory (asks for name)
        vars:
            dir:
                sh: |
                    read -p "Enter directory name (default: test-dir): " d
                    echo ${d:-test-dir}
        cmds:
            - mkdir -p {{.dir}}

    dir-remove:
        desc: Remove a directory (asks for name)
        vars:
            dir:
                sh: |
                    read -p "Enter directory to remove (default: test-dir): " d
                    echo ${d:-test-dir}
        cmds:
            - rmdir "{{.dir}}" || true

    file-copy:
        desc: Copy a file (asks for src and dest)
        vars:
            src:
                sh: |
                    read -p "Enter source file (default: /etc/hosts): " s
                    echo ${s:-/etc/hosts}
            dest:
                sh: |
                    read -p "Enter destination file (default: hosts.copy): " d
                    echo ${d:-hosts.copy}
        cmds:
            - cp "{{.src}}" "{{.dest}}"

    file-move:
        desc: Move/rename a file (asks for src and dest)
        vars:
            src:
                sh: |
                    read -p "Enter source file (default: hosts.copy): " s
                    echo ${s:-hosts.copy}
            dest:
                sh: |
                    read -p "Enter destination file (default: hosts.backup): " d
                    echo ${d:-hosts.backup}
        cmds:
            - mv "{{.src}}" "{{.dest}}" || true

    file-remove:
        desc: Remove a file (asks for path)
        vars:
            file:
                sh: |
                    read -p "Enter file to remove (default: hosts.backup): " f
                    echo ${f:-hosts.backup}
        cmds:
            - rm -f "{{.file}}"

    file-cat:
        desc: Display contents of a file
        vars:
            file:
                sh: |
                    read -p "Enter file to display (default: /etc/hostname): " f
                    echo ${f:-/etc/hostname}
        cmds:
            - cat "{{.file}}"

    file-head:
        desc: Display first N lines of a file
        vars:
            file:
                sh: |
                    read -p "Enter file (default: /etc/passwd): " f
                    echo ${f:-/etc/passwd}
            lines:
                sh: |
                    read -p "Enter number of lines (default: 5): " n
                    echo ${n:-5}
        cmds:
            - head -n {{.lines}} "{{.file}}"

    file-tail:
        desc: Display last N lines of a file
        vars:
            file:
                sh: |
                    read -p "Enter file (default: /etc/passwd): " f
                    echo ${f:-/etc/passwd}
            lines:
                sh: |
                    read -p "Enter number of lines (default: 5): " n
                    echo ${n:-5}
        cmds:
            - tail -n {{.lines}} "{{.file}}"

    file-search:
        desc: Search for a term in a file
        vars:
            term:
                sh: |
                    read -p "Enter search term (default: root): " t
                    echo ${t:-root}
            file:
                sh: |
                    read -p "Enter file to search (default: /etc/passwd): " f
                    echo ${f:-/etc/passwd}
        cmds:
            - grep "{{.term}}" "{{.file}}"

    file-count-lines:
        desc: Count lines in a file
        vars:
            file:
                sh: |
                    read -p "Enter file to count lines (default: /etc/passwd): " f
                    echo ${f:-/etc/passwd}
        cmds:
            - wc -l "{{.file}}"

    sys-processes:
        desc: List running processes
        cmds:
            - ps aux

    sys-kernel:
        desc: Show kernel version
        cmds:
            - uname -r

    sys-info:
        desc: Show system information
        cmds:
            - uname -a

    sys-block-devices:
        desc: List block devices
        cmds:
            - lsblk

    sys-usb:
        desc: List USB devices
        cmds:
            - lsusb || true

    sys-pci:
        desc: List PCI devices
        cmds:
            - lspci || true

    net-dns:
        desc: Resolve a hostname
        vars:
            host:
                sh: |
                    read -p "Enter hostname to resolve (default: google.com): " h
                    echo ${h:-google.com}
        cmds:
            - dig "{{.host}}" || nslookup "{{.host}}"

    net-ping:
        desc: Ping a host
        vars:
            host:
                sh: |
                    read -p "Enter hostname to ping (default: google.com): " h
                    echo ${h:-google.com}
        cmds:
            - ping -c 4 "{{.host}}"

    apt-update:
        desc: Update package lists (Debian/Ubuntu)
        cmds:
            - sudo apt update

    apt-upgrade:
        desc: Upgrade installed packages (Debian/Ubuntu)
        cmds:
            - sudo apt upgrade -y

    art:
        desc: Print some ASCII art
        cmds:
            - |
                echo "   _____         _      "
                echo "  |_   _|__  ___| |__   "
                echo "    | |/ _ \\/ __| '_ \\  "
                echo "    | |  __/\\__ \\ | | | "
                echo "    |_|\\___||___/_| |_| "
                echo ""
                echo "ASCII ART DEMO!"

    about:
        desc: Info about Task GUI
        cmds:
            - |
                echo "Task GUI - A simple frontend for Taskfile.dev"
                echo "Repository: https://github.com/Mgldvd/task-gui"
                echo "Version: Experimental"
