version: '3'

tasks:
  hello:
    desc: Test task that prints a message
    cmds:
      - echo "✓ Task execution successful!"
      - echo "This task was selected in the GUI and executed automatically"

  test-echo:
    desc: Another simple test
    cmds:
      - echo "Test command executed from GUI"
      - date

  list-files:
    desc: List files in current directory
    cmds:
      - ls -l

  show-disk-usage:
    desc: Show disk usage
    cmds:
      - df -h

  check-memory:
    desc: Show memory usage
    cmds:
      - free -h

  show-uptime:
    desc: Show system uptime
    cmds:
      - uptime

  check-ip:
    desc: Show IP address
    cmds:
      - ip addr show

  check-network:
    desc: Show network connections
    cmds:
      - netstat -tulnp || ss -tulnp

  show-users:
    desc: Show logged in users
    cmds:
      - who

  show-date:
    desc: Show current date and time
    cmds:
      - date

  calendar:
    desc: Show current month calendar
    cmds:
      - cal

  print-working-directory:
    desc: Print current directory
    cmds:
      - pwd

  make-directory:
    desc: Create a directory named test-dir
    cmds:
      - mkdir -p test-dir

  remove-directory:
    desc: Remove directory test-dir
    cmds:
      - rmdir test-dir || true

  copy-file:
    desc: Copy /etc/hosts to hosts.copy
    cmds:
      - cp /etc/hosts hosts.copy

  move-file:
    desc: Move hosts.copy to hosts.backup
    cmds:
      - mv hosts.copy hosts.backup || true

  remove-file:
    desc: Remove hosts.backup
    cmds:
      - rm -f hosts.backup

  show-file-content:
    desc: Display contents of /etc/hostname
    cmds:
      - cat /etc/hostname

  show-file-head:
    desc: Display first lines of /etc/passwd
    cmds:
      - head -n 5 /etc/passwd

  show-file-tail:
    desc: Display last lines of /etc/passwd
    cmds:
      - tail -n 5 /etc/passwd

  search-in-file:
    desc: Search for 'root' in /etc/passwd
    cmds:
      - grep root /etc/passwd

  count-lines:
    desc: Count lines in /etc/passwd
    cmds:
      - wc -l /etc/passwd

  show-processes:
    desc: List running processes
    cmds:
      - ps aux

  check-kernel:
    desc: Show kernel version
    cmds:
      - uname -r

  show-system-info:
    desc: Show system information
    cmds:
      - uname -a

  list-block-devices:
    desc: List block devices
    cmds:
      - lsblk

  list-usb:
    desc: List USB devices
    cmds:
      - lsusb || true

  list-pci:
    desc: List PCI devices
    cmds:
      - lspci || true

  check-dns:
    desc: Resolve google.com
    cmds:
      - dig google.com || nslookup google.com

  ping-test:
    desc: Ping google.com
    cmds:
      - ping -c 4 google.com

  update-system:
    desc: Update package lists (Debian/Ubuntu)
    cmds:
      - sudo apt update

  upgrade-system:
    desc: Upgrade installed packages (Debian/Ubuntu)
    cmds:
      - sudo apt upgrade -y
